version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 hello.py
       - run:
          name: Start Flask App
          command: |
            . venv/bin/activate
            export FLASK_APP=hello.py  # Replace with the actual module name
            python3 -m flask run --host=0.0.0.0 --port=5000
      
